export const GET_COMMON_CITIES_SUCCESS = 'GET_COMMON_CITIES_SUCCESS'
export const GET_COMMON_CITIES_FAIL = 'GET_COMMON_CITIES_FAIL'
export const GET_TRAFFIC_INFO_SUCCESS = 'GET_TRAFFIC_INFO_SUCCESS'
export const GET_TRAFFIC_INFO_INFO = 'GET_TRAFFIC_INFO_INFO'
