export const UPLOADING_PREVIEW_PHOTO = 'UPLOADING_PREVIEW_PHOTO'
export const UPLOADING_PREVIEW_PHOTO_SUCCESS = 'UPLOADING_PREVIEW_PHOTO_SUCCESS'
export const UPLOADING_PREVIEW_PHOTO_COMPLETE = 'UPLOADING_PREVIEW_PHOTO_COMPLETE'
