export const REQUESTING_EVALUATE_LIST = 'REQUESTING_EVALUATE_LIST'
export const REQUESTING_EVALUATE_LIST_SUCCESS = 'REQUESTING_EVALUATE_LIST_SUCCESS'
export const REQUESTING_EVALUATE_LIST_FAIL = 'REQUESTING_EVALUATE_LIST_FAIL'
