export const REQUESTING_SUBSTITUDE_INFO = 'REQUESTING_SUBSTITUDE_INFO'
export const REQUESTING_SUBSTITUDE_INFO_SUCCESS = 'REQUESTING_SUBSTITUDE_INFO_SUCCESS'
export const REQUESTING_SUBSTITUDE_INFO_FAIL = 'REQUESTING_SUBSTITUDE_INFO_FAIL'
export const HANDLE_SUBSTITUDE = 'HANDLE_SUBSTITUDE'
